// Because pre_built_step.bat for some reason isn't able to see node when I try it despite me being able to use it in a normal powershell window, you will just have to call this manually.
const fs = require("fs")
const path = require("path")
const { cwd } = require("process")

console.log("***********************************")
console.log(" *     Updating AutoGen Macros   * ")
console.log("***********************************")

var Path_Macros = path.join(cwd(), "scripts", "macros", "macros.gml")
var Content = fs.readFileSync(Path_Macros).toString()

var start = Content.match("#region AUTOGEN");
var end = Content.match("#endregion AUTOGEN");

if ((!start != undefined) && (end != undefined)) {
	var Contentpart0 = Content.slice(0, start.index)
	var Contentpart1 = Content.slice(end.index)
	var autogeneratedata = "#region AUTOGEN [Use node on updateautogeneratedmacros.js to update the Autogenerated Macros]"
	console.log("found autogenerate area.")
	var macrodatas = [
		function() { // __AUTOGENMACRO__84DEBUGROOMDATA__
			var data = "group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, \"Rooms\"); scr_84_push(parent); parent = group; "
			var Path_Rooms = path.join(cwd(), "rooms")
			var folderlist = fs.readdirSync(Path_Rooms);
			if (folderlist != undefined) {
				var generatedfilelist = {}
				console.log(folderlist)
				for (var j = 0; j < folderlist.length; j++) {
					var RoomName = folderlist[j].toString()
					var Path_Room = path.join(Path_Rooms, RoomName, RoomName + ".yy")
					var STRDAT = fs.readFileSync(Path_Room).toString()
					var DATA = JSON.parse(STRDAT.replace(/,(\s*[}\]])/g, '$1'));
					//console.log(DATA);
					var parentname = DATA.parent.name.toString();
					var dark = (STRDAT.match("obj_darkcontroller") != undefined)
					if (!(parentname in generatedfilelist)) { generatedfilelist[parentname] = [] }
					generatedfilelist[parentname].push([RoomName, dark])

				}
				
				var folders = Object.keys(generatedfilelist)
				
				for (var j = 0; j < folders.length; j++) {
					var foldername = folders[j].toString()
					data += "group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, \"" + foldername + "\"); scr_84_push(parent); parent = group; "
					for (var jj = 0; jj < generatedfilelist[foldername].length; jj++) {
						console.log(generatedfilelist[foldername][jj])
						var name = generatedfilelist[foldername][jj][0].toString()
						var isdark = generatedfilelist[foldername][jj][1] == true
						console.log("name: " + name + ", DarkZone: " + isdark.toString())
						data += "scr_84_add_menu_item(parent, " + (isdark ? "roomtransitiondata_dark" : "roomtransitiondata_light") + ", " + name + ", \"" + name + "\")"
					}
					data += "parent = scr_84_pop()"
				}
			}
			data += "parent = scr_84_pop();"
			return data
		}
	]
	var macrolist = [
		"__AUTOGENMACRO__84DEBUGROOMDATA__"
	]
	
	for (var i = 0; i < macrolist.length; i++) {
		console.log("**** Generating " + macrolist[i].toString());
		autogeneratedata += "\n		#macro " + macrolist[i].toString();
		autogeneratedata += " " + macrodatas[i]().toString();
	}
	//console.log(autogeneratedata);
	Content = Contentpart0 + autogeneratedata + "\n	" + Contentpart1
	//console.log(Content)
} else {
	console.log("Failed to find autogenerate area.")
}

fs.writeFileSync(Path_Macros, Content);
console.log("***********************************")
console.log(" *     Updated AutoGen Macros   * ")
console.log("***********************************")
