function macros(){
	#macro KEYITEMDATASTART 10000
	#macro SCRSPELL_ItemsStart 10000
	#macro DEBUGMODE false
	#macro Debug:DEBUGMODE true
	
	#macro MusicFolder "mus/"
	
	#macro PrimaryBattleMusic "rudebuster_boss.ogg"
	
	#macro INVENTORYMAX_ARMORANDWEAPONS 48
	
	#macro INVENTORYMAX_STORAGE ((global.chapter - (global.chapter >= 3 ? 1 : 0)) * 12)
	#macro INVENTORYMAX_STORAGEARRAYSIZE (6 * 12) // 7 Chapters, Excluding Ch3, Just like Deltarune has for it
	
	#macro NPCSIGNDEBUGBOUNDSDISPLAYALPHA 0
	#macro chaseenemy_drawdebugbox 1
	#macro customdebug_chaseenemy_drawcurrentpacetype 0
	
	#macro IncludeRemovedDebugSoulSlowLock 1
	#macro DamageInLightDeductsFromLightHP 1 // if 0 it'll do the normal behavior of only dealing with Dark HP
	#macro OverworldBattleMode_UsebattleheartasHitbox 1 // Normal Behavior in Deltarune is a very badly made hitbox.
	
	#region global.interact modes
	// Base Deltarune
	#macro GLOBALINTERACTTYPE_canmove 0 /* Normal Moving */
	#macro GLOBALINTERACTTYPE_noinput 1 /* Cutscenes, NPC Textboxes, Small stuff like that */
	#macro GLOBALINTERACTTYPE_inbattle 2 /* Darkworld Battles */
	#macro GLOBALINTERACTTYPE_roomtransition 3 /* Room Transitions Through Doors */
	#macro GLOBALINTERACTTYPE_swordmode_ATK 4 /* UNUSED, Sword Mode Attack for Original Version of the Weird Route. */
	#macro GLOBALINTERACTTYPE_inmenu 5 /* Menu */
	#macro GLOBALINTERACTTYPE_inmenutextbox 6 /* Textbox Opened Through Menu */
	#macro GLOBALINTERACTTYPE_climbing_roomtransition 7 /* Room Transition while Climbing */
	#endregion
	
	
	#region AUTOGEN [Use node on updateautogeneratedmacros.js to update the Autogenerated Macros]
		#macro __AUTOGENMACRO__84DEBUGROOMDATA__ group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "Rooms"); scr_84_push(parent); parent = group; group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "Contact"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_light, ROOM_INITIALIZE, "ROOM_INITIALIZE"); scr_84_add_menu_item(parent, roomtransitiondata_light, PLACE_LOGO, "PLACE_LOGO"); scr_84_add_menu_item(parent, roomtransitiondata_light, PLACE_MENU, "PLACE_MENU"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_legend, "room_legend"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_intro, "room_intro"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_gameover, "room_gameover"); scr_84_add_menu_item(parent, roomtransitiondata_light, PLACE_FAILURE, "PLACE_FAILURE"); parent = scr_84_pop(); group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "Templates"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_dark, room_DARKbase_GMS2, "room_DARKbase_GMS2"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_LIGHTbase, "room_LIGHTbase"); parent = scr_84_pop(); group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "Dark"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_dark, room_dw_test, "room_dw_test"); scr_84_add_menu_item(parent, roomtransitiondata_dark, room_dw_castle_area_1, "room_dw_castle_area_1"); parent = scr_84_pop(); group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "Light"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_light, room_lw_test, "room_lw_test"); parent = scr_84_pop(); group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "lightworld_exterior"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_krisyard, "room_town_krisyard"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_northwest, "room_town_northwest"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_north, "room_town_north"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_beach, "room_beach"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_mid, "room_town_mid"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_apartments, "room_town_apartments"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_south, "room_town_south"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_school, "room_town_school"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_church, "room_town_church"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_graveyard, "room_graveyard"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_town_shelter, "room_town_shelter"); parent = scr_84_pop(); group = ds_list_create(); scr_84_add_menu_item(parent, groupdata, group, "lightworld_interior"); scr_84_push(parent); parent = group; scr_84_add_menu_item(parent, roomtransitiondata_light, room_hospital_lobby, "room_hospital_lobby"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_hospital_hallway, "room_hospital_hallway"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_hospital_rudy, "room_hospital_rudy"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_hospital_room2, "room_hospital_room2"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_diner, "room_diner"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_townhall, "room_townhall"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_flowershop_1f, "room_flowershop_1f"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_flowershop_2f, "room_flowershop_2f"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_library, "room_library"); scr_84_add_menu_item(parent, roomtransitiondata_light, room_alphysalley, "room_alphysalley"); parent = scr_84_pop(); parent = scr_84_pop()
	#endregion AUTOGEN
}